version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "9000:9000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database
    env_file:
      - ./backend/.env
    command: bash -c "flask db migrate && flask db upgrade && gunicorn -b 0.0.0.0:5000 app:app"


  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: template1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: veryunsafepassword
    ports:
      - "5432:5432"
    volumes:      
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: